name: コンパイル

on:
  push:
    branches: latest_libctru
jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    
    steps:
    - uses: actions/checkout@v4
      
    - name: つくる
      run: make
      
    - name: あげる
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ./
