name: コンパイル

on:
  push:
    branches: objects
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: つくる
      run: make
      
    - name: あげる
      uses: actions/upload-artifact@v4
      with:
        name: out
        path: ./
